1. Use f-string para concaternar textos o valores numéricos. De 2 ejemplos.

In [19]:
a1<-'Hi'
print(a1)

[1] "Hi"


In [20]:
a2<-'How r u?'
print(a2)

[1] "How r u?"


In [21]:
a3<-'Welcome to'

In [22]:
#install.packages("devtools")
library(glue)
z<- glue('{a1}, {a2}','\n')
x<-glue('{a3} my first homework')
print(z)
print(x)

sprintf('%s, %s', a1, a2,'\n')
sprintf('%s, %s', a3, 'my first homework')

Hi, How r u?
Welcome to my first homework


[1] "Hi, How r u?"

[1] "Welcome to, my first homework"

2. Crear una Lista de 3 distritos de Lima, añadir 2 distritos del Callao. Extraer el primer y último elemento usando el Indexing

In [23]:
distrito <-list('SAN JUAN DE LURIGANCHO', 'PUEBLO LIBRE', 'COMAS', 'BELLAVISTA','CALLAO')
distrito

[[1]]
[1] "SAN JUAN DE LURIGANCHO"

[[2]]
[1] "PUEBLO LIBRE"

[[3]]
[1] "COMAS"

[[4]]
[1] "BELLAVISTA"

[[5]]
[1] "CALLAO"

In [24]:
Primero<-distrito[1]
Ultimo<-distrito[5]
print(Primero)
print(Ultimo)

[[1]]
[1] "SAN JUAN DE LURIGANCHO"

[[1]]
[1] "CALLAO"



3. Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [25]:
Postal_code <-list(SAN_JUAN_DE_LURIGANCHO=list(UBIGEO=150132,Poverty_Rate="20,0%",Population="1 177 629"),PUEBLO_LIBRE=list(UBIGEO=150121,Poverty_Rate=" 1,2%",Population="94 010"),COMAS=list(UBIGEO=150110,Poverty_Rate="19,2%",Population="573 884"),BELLAVISTA=list(UBIGEO=200602,Poverty_Rate=" 26,4%",Population="38 905"),CALLAO=list(UBIGEO=70101,Poverty_Rate="16,6%",Population=" 512 386"))
Postal_code

$SAN_JUAN_DE_LURIGANCHO
$SAN_JUAN_DE_LURIGANCHO$UBIGEO
[1] 150132

$SAN_JUAN_DE_LURIGANCHO$Poverty_Rate
[1] "20,0%"

$SAN_JUAN_DE_LURIGANCHO$Population
[1] "1 177 629"


$PUEBLO_LIBRE
$PUEBLO_LIBRE$UBIGEO
[1] 150121

$PUEBLO_LIBRE$Poverty_Rate
[1] " 1,2%"

$PUEBLO_LIBRE$Population
[1] "94 010"


$COMAS
$COMAS$UBIGEO
[1] 150110

$COMAS$Poverty_Rate
[1] "19,2%"

$COMAS$Population
[1] "573 884"


$BELLAVISTA
$BELLAVISTA$UBIGEO
[1] 200602

$BELLAVISTA$Poverty_Rate
[1] " 26,4%"

$BELLAVISTA$Population
[1] "38 905"


$CALLAO
$CALLAO$UBIGEO
[1] 70101

$CALLAO$Poverty_Rate
[1] "16,6%"

$CALLAO$Population
[1] " 512 386"

4. Muestre la información de pobreza y de población de 3 distritos

In [27]:
Postal_code$COMAS$Poverty_Rate

[1] "19,2%"

In [28]:
Postal_code$COMAS$Population

[1] "573 884"

In [29]:
Postal_code$BELLAVISTA$Poverty_Rate

[1] " 26,4%"

In [30]:
Postal_code$BELLAVISTA$Population

[1] "38 905"

In [31]:
Postal_code$PUEBLO_LIBRE$Poverty_Rate 

[1] " 1,2%"

In [32]:
Postal_code$PUEBLO_LIBRE$Population

[1] "94 010"

In [33]:
cat("COMAS", "\n", "Poverty Rate:", Postal_code$COMAS$Poverty_Rate, "\n", "Population:", Postal_code$COMAS$Population )

COMAS 
 Poverty Rate: 19,2% 
 Population: 573 884

In [34]:
cat("BELLAVISTA", "\n", "Poverty Rate:", Postal_code$BELLAVISTA$Poverty_Rate, "\n", "Population:", Postal_code$BELLAVISTA$Population )

BELLAVISTA 
 Poverty Rate:  26,4% 
 Population: 38 905

In [35]:
cat("PUEBLO_LIBRE", "\n", "Poverty Rate:", Postal_code$PUEBLO_LIBRE$Poverty_Rate, "\n", "Population:", Postal_code$PUEBLO_LIBRE$Population )

PUEBLO_LIBRE 
 Poverty Rate:  1,2% 
 Population: 94 010

5. Crear 2 matrices y dar 2 ejemplos de concatenacion

In [36]:
M1 <- matrix(0,6,4)

print(M1)

     [,1] [,2] [,3] [,4]
[1,]    0    0    0    0
[2,]    0    0    0    0
[3,]    0    0    0    0
[4,]    0    0    0    0
[5,]    0    0    0    0
[6,]    0    0    0    0


In [37]:
M2 <- matrix(1,6, 4) 
print(M2)

     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    1    1    1    1
[3,]    1    1    1    1
[4,]    1    1    1    1
[5,]    1    1    1    1
[6,]    1    1    1    1


In [38]:
M3 <- cbind(M1,M2)
M3

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0    0    0    0    1    1    1    1   
[2,] 0    0    0    0    1    1    1    1   
[3,] 0    0    0    0    1    1    1    1   
[4,] 0    0    0    0    1    1    1    1   
[5,] 0    0    0    0    1    1    1    1   
[6,] 0    0    0    0    1    1    1    1

In [39]:
M4 <- rbind(M1,M2)
M4

[,1] [,2] [,3] [,4]
 [1,] 0    0    0    0   
 [2,] 0    0    0    0   
 [3,] 0    0    0    0   
 [4,] 0    0    0    0   
 [5,] 0    0    0    0   
 [6,] 0    0    0    0   
 [7,] 1    1    1    1   
 [8,] 1    1    1    1   
 [9,] 1    1    1    1   
[10,] 1    1    1    1   
[11,] 1    1    1    1   
[12,] 1    1    1    1

 6. Crear una matriz de dimensión 4x8, seleccionar las ultimas dos columnas y primeras 3 filas.

In [44]:
A <- matrix(c(seq(0, 7), seq( 8, 15), seq( 16, 23), seq( 24, 31)), nrow = 4, byrow =TRUE)
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6    7  
[2,]  8    9   10   11   12   13   14   15  
[3,] 16   17   18   19   20   21   22   23  
[4,] 24   25   26   27   28   29   30   31

In [45]:
A[1:3,] # rows selection

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6    7  
[2,]  8    9   10   11   12   13   14   15  
[3,] 16   17   18   19   20   21   22   23

In [46]:
A[,7:8]  # columns selection

[,1] [,2]
[1,]  6    7  
[2,] 14   15  
[3,] 22   23  
[4,] 30   31

7. Obtener el estimador de la varianza del termino de perturbación

In [55]:
set.seed(756)

#x1 = runif(500, min = 0, max = 1)
x1 <- runif(500)
x2 <- runif(500)
x3 <- runif(500)
x4 <- runif(500)
#random.seed(123)
e <- rnorm(500)

# Poblacional regression (Data Generating Process GDP)

Y <- 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

In [56]:
X <- cbind(matrix(1,500), x1,x2,x3,x4)
X

x1         x2          x3         x4        
 [1,] 1   0.18667121 0.14026657  0.94280410 0.10649518
 [2,] 1   0.94443903 0.13706934  0.52276689 0.52940151
 [3,] 1   0.92838826 0.71164475  0.64336073 0.71860641
 [4,] 1   0.95917710 0.18051582  0.69677409 0.25410129
 [5,] 1   0.52417646 0.08842863  0.19106442 0.40701648
 [6,] 1   0.76715036 0.21311299  0.76912339 0.23444981
 [7,] 1   0.11651188 0.23825413  0.93014166 0.99164182
 [8,] 1   0.22528155 0.07474239  0.94627987 0.67382932
 [9,] 1   0.50887578 0.59305166  0.19104230 0.68902774
[10,] 1   0.48288501 0.43254095  0.65083054 0.12949274
[11,] 1   0.99894565 0.69434619  0.01480160 0.42898919
[12,] 1   0.05084642 0.91495662  0.33351877 0.63241673
[13,] 1   0.06691185 0.19109222  0.08920029 0.76341623
[14,] 1   0.11794333 0.35745388  0.81815994 0.66611022
[15,] 1   0.68559683 0.27811306  0.66970300 0.05112475
[16,] 1   0.71863128 0.46288762  0.80392381 0.89823474
[17,] 1   0.06124421 0.84306605  0.37011961 0.92389927
[18,] 1   0.62285430 0.31216241  0.98473847 0.79780304
[19,] 1   0.55798855 0.75144188  0.52716798 0.65260034
[20,] 1   0.90502225 0.22930374  0.39986640 0.91896482
[21,] 1   0.92542007 0.65874796  0.69178055 0.09224323
[22,] 1   0.08820010 0.14306197  0.03249294 0.14938501
[23,] 1   0.31211653 0.56704057  0.32759226 0.80864499
[24,] 1   0.20291122 0.42337361  0.09160377 0.86773079
[25,] 1   0.71595446 0.59810639  0.30404230 0.34511233
[26,] 1   0.90460165 0.45845377  0.65259555 0.88972366
[27,] 1   0.46766476 0.52513082  0.71309737 0.16936588
[28,] 1   0.64029220 0.56341941  0.47951154 0.72864526
[29,] 1   0.96117897 0.44741020  0.60329951 0.69625929
[30,] 1   0.06439775 0.81046488  0.52349975 0.54737779
[31,] ... ...        ...         ...        ...       
[32,] 1   0.95949565 0.675293292 0.8533642  0.02793749
[33,] 1   0.97966608 0.039872393 0.9416000  0.72198486
[34,] 1   0.52690660 0.977472335 0.6314807  0.56772196
[35,] 1   0.04598748 0.317146298 0.7144303  0.44446465
[36,] 1   0.90023072 0.205296297 0.6285209  0.60478397
[37,] 1   0.32258687 0.194069347 0.1173722  0.98242966
[38,] 1   0.40783653 0.555588038 0.5186564  0.50368648
[39,] 1   0.99673296 0.999136477 0.7249953  0.92376843
[40,] 1   0.91272255 0.241522007 0.7817168  0.99709942
[41,] 1   0.29021141 0.710598734 0.2612493  0.48444181
[42,] 1   0.69542780 0.276058567 0.9691086  0.17449112
[43,] 1   0.04131045 0.276989744 0.8094209  0.15243695
[44,] 1   0.71684108 0.512455887 0.8306769  0.01123611
[45,] 1   0.76262139 0.059084704 0.3211154  0.45001308
[46,] 1   0.15972753 0.833049576 0.2579192  0.15601347
[47,] 1   0.92483975 0.936467176 0.4144494  0.94711103
[48,] 1   0.81208558 0.555141241 0.3050448  0.66984936
[49,] 1   0.77316963 0.337681846 0.1429613  0.95666772
[50,] 1   0.35355523 0.450951844 0.3189683  0.73501092
[51,] 1   0.12435475 0.560914025 0.7513311  0.43392086
[52,] 1   0.88780212 0.681851396 0.3224342  0.22024524
[53,] 1   0.85313819 0.875375814 0.8255444  0.34645350
[54,] 1   0.84449228 0.617045320 0.8734211  0.16636795
[55,] 1   0.34172408 0.725208323 0.2835125  0.16518848
[56,] 1   0.28166291 0.007400454 0.3206765  0.12923063
[57,] 1   0.12384033 0.899060817 0.9858464  0.85039734
[58,] 1   0.73414969 0.561721307 0.3043357  0.91251808
[59,] 1   0.77999513 0.101500033 0.7807000  0.07230745
[60,] 1   0.92141159 0.072265238 0.8283349  0.79017804
[61,] 1   0.06351236 0.507830425 0.9885709  0.24619645

In [57]:
beta <- solve(t(X) %*% X) %*% (t(X) %*% Y)
beta

[,1]     
   1.1294850
x1 0.9372619
x2 1.0652342
x3 0.3915098
x4 1.3708041

In [58]:
Y_hat <- X %*% beta
Y_hat

[,1]    
 [1,] 1.968963
 [2,] 3.091057
 [3,] 3.994647
 [4,] 2.841894
 [5,] 2.347716
 [6,] 2.698025
 [7,] 3.215990
 [8,] 2.714417
 [9,] 3.257491
[10,] 2.475148
[11,] 3.399255
[12,] 3.149280
[13,] 2.477174
[14,] 2.854225
[15,] 2.400602
[16,] 3.842162
[17,] 3.496340
[18,] 3.524955
[19,] 3.553907
[20,] 3.638262
[21,] 3.095853
[22,] 1.582045
[23,] 3.262800
[24,] 2.996011
[25,] 3.029762
[26,] 3.940829
[27,] 2.638549
[28,] 3.516343
[29,] 3.697591
[30,] 3.008480
[31,] ...     
[32,] 3.120526
[33,] 3.448508
[34,] 3.690038
[35,] 2.399403
[36,] 3.267038
[37,] 3.031234
[38,] 2.997081
[39,] 4.678147
[40,] 3.915100
[41,] 2.924800
[42,] 2.693959
[43,] 1.989120
[44,] 2.687859
[45,] 2.649800
[46,] 2.481426
[47,] 4.454424
[48,] 3.519638
[49,] 3.581232
[50,] 3.073663
[51,] 2.732517
[52,] 3.116069
[53,] 3.659708
[54,] 3.148304
[55,] 2.559726
[56,] 1.704058
[57,] 3.754963
[58,] 3.785974
[59,] 2.373437
[60,] 3.477549
[61,] 2.454493

In [59]:
U_hat <- Y - Y_hat
U_hat

[,1]        
 [1,]  0.43372226 
 [2,] -0.85432933 
 [3,] -0.83587065 
 [4,]  0.27985232 
 [5,]  1.70601560 
 [6,] -1.33152955 
 [7,] -0.14388449 
 [8,] -1.05654689 
 [9,]  0.04821029 
[10,]  0.08383981 
[11,]  1.58892027 
[12,]  1.34537807 
[13,] -0.41960163 
[14,] -0.10462227 
[15,] -0.55915252 
[16,]  2.04259087 
[17,] -1.56916536 
[18,] -0.88482503 
[19,]  1.28665754 
[20,]  1.20929716 
[21,] -0.56396357 
[22,] -1.54832459 
[23,] -0.94693670 
[24,]  0.91577549 
[25,]  0.96185798 
[26,]  0.47570405 
[27,] -1.20882839 
[28,] -0.81176472 
[29,] -1.31738220 
[30,]  0.48629048 
[31,] ...         
[32,] -0.162618228
[33,] -1.367137693
[34,]  1.222009939
[35,] -0.608604249
[36,] -0.110432797
[37,]  0.714795832
[38,] -0.349693467
[39,]  0.025894789
[40,]  0.858142636
[41,] -1.883076751
[42,]  0.488302903
[43,] -0.984598073
[44,] -0.108765933
[45,]  0.290679532
[46,] -0.007500173
[47,] -1.707895403
[48,]  0.343204281
[49,]  1.151756392
[50,] -0.086668357
[51,] -0.078314440
[52,]  2.915950135
[53,]  0.836701832
[54,] -1.389491981
[55,] -0.781432843
[56,] -0.525050619
[57,] -0.802642337
[58,] -2.406318729
[59,]  1.205802843
[60,]  1.678856222
[61,] -1.407873778

In [60]:
t(U_hat)

[,1]      [,2]       [,3]       [,4]      [,5]     [,6]     [,7]      
[1,] 0.4337223 -0.8543293 -0.8358706 0.2798523 1.706016 -1.33153 -0.1438845
     [,8]      [,9]       [,10]      [,11] [,12]   [,13]     [,14]    
[1,] -1.056547 0.04821029 0.08383981 ...   2.91595 0.8367018 -1.389492
     [,15]      [,16]      [,17]      [,18]     [,19]    [,20]    [,21]    
[1,] -0.7814328 -0.5250506 -0.8026423 -2.406319 1.205803 1.678856 -1.407874

In [62]:
t(U_hat) %*% U_hat

[,1]    
[1,] 510.2016

In [63]:
SCR <- t(U_hat) %*% U_hat
SCR

[,1]    
[1,] 510.2016

In [83]:
Estimador_de_la_varianza_del_termino_de_pertubacion <- SCR/(500-5)
Estimador_de_la_varianza_del_termino_de_pertubacion

[,1]   
[1,] 1.03071

8. Matriz de varianza y covarianza de los coeficientes

In [87]:
drop(Estimador_de_la_varianza_del_termino_de_pertubacion)* solve(t(X) %*% X)


x1            x2            x3            x4           
    0.02637547 -0.0107577256 -0.0125223845 -0.0129083837 -0.0119220529
x1 -0.01075773  0.0226380977  0.0006594612  0.0004359917 -0.0022281607
x2 -0.01252238  0.0006594612  0.0260365322 -0.0001631863 -0.0008748490
x3 -0.01290838  0.0004359917 -0.0001631863  0.0253669356 -0.0003919564
x4 -0.01192205 -0.0022281607 -0.0008748490 -0.0003919564  0.0263347481

9. Matriz generador de residuos

In [85]:
I <- diag(500)
I

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ...   0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ...   0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ...   0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ...   0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ...   0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ...   0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ...   0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ...   0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ...   0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ...   0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[16,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[24,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[25,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[26,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[27,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[28,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[29,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[30,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[31,] ...  ...  ...  ...  ...  ...  ...  ...  ...  ...         ...   ...  
[32,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[33,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[34,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[35,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[36,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[37,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[38,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[39,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[40,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[41,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[42,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[43,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[44,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[45,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[46,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[47,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[48,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[49,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[50,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[51,] 0    0    0    0    0    0    0    0    0    0     ...   0     0    
[52,] 0    0    0    0    0    0    0    0    0    0     ...   1     0    
[53,] 0    0    0    0    0    

In [88]:
M = I-X %*% solve(t(X) %*% X) %*% t(X)
M

[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  0.9844125842 -0.0024026222  3.064232e-03 -0.0064729214 -3.024371e-03
 [2,] -0.0024026222  0.9907793004 -4.106278e-03 -0.0091856335 -5.536260e-03
 [3,]  0.0030642317 -0.0041062782  9.916146e-01 -0.0039818871  1.589553e-03
 [4,] -0.0064729214 -0.0091856335 -3.981887e-03  0.9880404686 -4.430886e-03
 [5,] -0.0030243713 -0.0055362601  1.589553e-03 -0.0044308864  9.912430e-01
 [6,] -0.0083207741 -0.0071315668 -2.577855e-03 -0.0102105957 -3.528453e-03
 [7,] -0.0064135887 -0.0005357530 -2.985479e-04  0.0017378988  4.336160e-05
 [8,] -0.0104432095 -0.0031091071  8.402525e-04 -0.0030808721 -2.273527e-03
 [9,]  0.0040294486 -0.0009321296 -2.262471e-03  0.0015480587 -3.037656e-03
[10,] -0.0078896698 -0.0025295106 -4.303840e-04 -0.0058401622 -2.425103e-03
[11,]  0.0072481216 -0.0047126365 -5.705370e-03 -0.0039565299 -4.198240e-03
[12,]  0.0019795879  0.0060823362 -1.693771e-04  0.0075763323  1.287985e-03
[13,] -0.0003519329 -0.0001268947  4.111456e-03  0.0043120088 -7.501305e-03
[14,] -0.0073334122  0.0004062691  6.611630e-04  0.0006794714 -4.373398e-04
[15,] -0.0089691283 -0.0058205551 -1.152906e-03 -0.0097798453 -4.075355e-03
[16,] -0.0003517090 -0.0042746245 -6.290509e-03 -0.0030261922  8.699769e-04
[17,]  0.0038592274  0.0054613988 -1.123067e-03  0.0089682267  1.566786e-03
[18,] -0.0051600775 -0.0047996936 -4.759951e-03 -0.0047687718  5.600516e-04
[19,]  0.0017606426 -0.0002215578 -4.586515e-03  0.0002649730  1.044902e-03
[20,]  0.0032664463 -0.0078343017 -5.399576e-03 -0.0045482952 -4.605811e-03
[21,] -0.0040259298 -0.0048078647 -5.750331e-03 -0.0093136935 -9.351884e-05
[22,] -0.0060077877 -0.0009568598  6.797511e-03 -0.0006297610 -9.930496e-03
[23,]  0.0023093756  0.0006839148 -1.241992e-03  0.0036575329 -1.877414e-03
[24,]  0.0034907005  0.0006263570  1.125119e-03  0.0053587865 -4.959978e-03
[25,]  0.0007784613 -0.0030449776 -3.201920e-03 -0.0037438575 -3.020510e-03
[26,]  0.0022759062 -0.0059989514 -7.427201e-03 -0.0043316362 -4.325514e-04
[27,] -0.0074523856 -0.0016041844 -1.183660e-03 -0.0050081743 -9.168762e-04
[28,]  0.0018696437 -0.0025658270 -4.405606e-03 -0.0011621816 -1.038471e-03
[29,]  0.0011689056 -0.0066812146 -6.955193e-03 -0.0062277994 -1.417979e-03
[30,] -0.0017090572  0.0049215262  8.288192e-06  0.0050959042  1.510829e-03
[31,] ...           ...           ...           ...           ...          
[32,] -6.028201e-03 -0.0050973915 -0.0064385340 -1.082951e-02  0.0011576733
[33,] -5.643206e-03 -0.0105323056 -0.0060204424 -1.086219e-02 -0.0027904421
[34,]  1.602764e-03  0.0019321528 -0.0056050965  1.087552e-03  0.0039081209
[35,] -9.169017e-03  0.0007062048  0.0027649723 -2.818397e-05 -0.0021631655
[36,] -2.473888e-03 -0.0082391624 -0.0047399363 -8.172068e-03 -0.0038361589
[37,]  3.057284e-03 -0.0024501873  0.0008048613  3.170455e-03 -0.0068017523
[38,] -2.218633e-03 -0.0005415219 -0.0014830963 -6.748414e-04 -0.0012856907
[39,]  7.110870e-03 -0.0022377016 -0.0117294249 -1.447845e-03  0.0055655053
[40,]  9.563798e-05 -0.0079689432 -0.0071138448 -5.821709e-03 -0.0013290178
[41,]  9.850210e-04  0.0020336444 -0.0003649598  2.807965e-03 -0.0017500349
[42,] -1.092974e-02 -0.0060376017 -0.0027097982 -1.043319e-02 -0.0014710979
[43,] -1.340443e-02  0.0002392595  0.0038718726 -2.947817e-03 -0.0025384598
[44,] -8.844027e-03 -0.0041970000 -0.0031529370 -9.487946e-03 -0.0005998155
[45,] -2.803744e-03 -0.0080975873 -0.0010199961 -7.459195e-03 -0.0080130025
[46,] -1.898641e-03  0.0041954764  0.0014312804  2.602291e-03 -0.0013174553
[47,]  9.675607e-03 -0.0019263947 -0.0097772963  5.486654e-04  0.0026101983
[48,]  4.135900e-03 -0.0041969915 -0.0051161793 -2.613938e-03 -0.0026774181
[49,]  6.525243e-03 -0.0055037488 -0.0041112471 -8.283101e-04 -0.0053863530
[50,]  9.242594e-04 -0.0007333806 -0.0006388307  1.860347e-03 -0.0032942596
[51,] -7.062698e-03  0.0020406785  0.0005769810  6.688045e-04  0.0004984922
[52,]  1.142585e-03 -0.0040101764 -0.0048178960 -5.970