1. Use f-string para concaternar textos o valores numéricos. De 2 ejemplos.

In [13]:
a1='Hi'
print(a1)

Hi


In [14]:
a2='How r u?'
print(a2)

How r u?


In [15]:
a3='Welcome to'

In [16]:
print(f'{a1}, {a2}','\n')
print(f'{a3} my first homework')

Hi, How r u? 

Welcome to my first homework


2. Crear una Lista de 3 distritos de Lima, añadir 2 distritos del Callao. Extraer el primer y último elemento usando el Indexing

In [17]:
distrito = ['SAN JUAN DE LURIGANCHO', 'PUEBLO LIBRE', 'COMAS', 'BELLAVISTA','CALLAO']
distrito

['SAN JUAN DE LURIGANCHO', 'PUEBLO LIBRE', 'COMAS', 'BELLAVISTA', 'CALLAO']

In [18]:
Primero=distrito[0]
Ultimo=distrito[-1]
print(Primero)
print(Ultimo)

SAN JUAN DE LURIGANCHO
CALLAO


3. Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [19]:
Postal_code = {'SAN JUAN DE LURIGANCHO':{"UBIGEO":150132,"Poverty Rate":"20,0%","Population":"1 177 629"},'PUEBLO LIBRE':{"UBIGEO":150121,"Poverty Rate":" 1,2%","Population":"94 010"},'COMAS':{"UBIGEO":150110,"Poverty Rate":"19,2%","Population":"573 884"},'BELLAVISTA':{"UBIGEO":200602,"Poverty Rate":" 26,4%","Population":"38 905"},'CALLAO':{"UBIGEO":70101,"Poverty Rate":"16,6%","Population":" 512 386"}}
Postal_code

{'SAN JUAN DE LURIGANCHO': {'UBIGEO': 150132,
  'Poverty Rate': '20,0%',
  'Population': '1 177 629'},
 'PUEBLO LIBRE': {'UBIGEO': 150121,
  'Poverty Rate': ' 1,2%',
  'Population': '94 010'},
 'COMAS': {'UBIGEO': 150110, 'Poverty Rate': '19,2%', 'Population': '573 884'},
 'BELLAVISTA': {'UBIGEO': 200602,
  'Poverty Rate': ' 26,4%',
  'Population': '38 905'},
 'CALLAO': {'UBIGEO': 70101,
  'Poverty Rate': '16,6%',
  'Population': ' 512 386'}}

4. Muestre la información de pobreza y de población de 3 distritos

In [32]:
Postal_code['CALLAO']['Poverty Rate']


'16,6%'

In [33]:
Postal_code['CALLAO']['Population']

' 512 386'

In [34]:
Postal_code['PUEBLO LIBRE']['Poverty Rate']

' 1,2%'

In [35]:
Postal_code['PUEBLO LIBRE']['Population']

'94 010'

In [36]:
Postal_code['BELLAVISTA']['Poverty Rate']

' 26,4%'

In [37]:
Postal_code['BELLAVISTA']['Population']

'38 905'

In [39]:
print("CALLAO", "\n", "Poverty Rate:", Postal_code['CALLAO']['Poverty Rate'], "\n", "Population:", Postal_code['CALLAO']['Population'] )



CALLAO 
 Poverty Rate: 16,6% 
 Population:  512 386


In [40]:
print("PUEBLO LIBRE", "\n", "Poverty Rate:", Postal_code['PUEBLO LIBRE']['Poverty Rate'], "\n", "Population:", Postal_code['PUEBLO LIBRE']['Population'] )


PUEBLO LIBRE 
 Poverty Rate:  1,2% 
 Population: 94 010


In [41]:
print("BELLAVISTA", "\n", "Poverty Rate:", Postal_code['BELLAVISTA']['Poverty Rate'], "\n", "Population:", Postal_code['BELLAVISTA']['Population'] )


BELLAVISTA 
 Poverty Rate:  26,4% 
 Population: 38 905


5. Crear matrices y dar dos ejemplos de concatenación. Unión vertical y horizontal.

In [42]:
import numpy as np
import pandas as pd

In [43]:
M1 = np.zeros( (6, 3) )
print(M1)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
M2 = np.ones( (6, 3) )
print(M2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [46]:
M3 = np.hstack((M1,M2))
M3

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [47]:
con1 = np.concatenate((M1,M2), axis = 1) # add more columns. This is a horizontal operation
con1

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [48]:
con2 = np.concatenate((M1,M2), axis = 0) # add more rows. This is a vertical operation
con2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

6. Crear una matriz de dimensión 4x8, seleccionar las ultimas dos columnas y primeras 3 filas

In [49]:
M4 = np.array([[2,2,3,4,5,1,8,14],[1,5,5,9,8,2,28,0],[10,9,5,7,3,2,1,9],[7,3,5,7,8,3,5,2]])
print(M4)

[[ 2  2  3  4  5  1  8 14]
 [ 1  5  5  9  8  2 28  0]
 [10  9  5  7  3  2  1  9]
 [ 7  3  5  7  8  3  5  2]]


In [50]:
M4[:,6:8]  # columns selection

array([[ 8, 14],
       [28,  0],
       [ 1,  9],
       [ 5,  2]])

In [53]:
M4[0:3,:]  # rows selection

array([[ 2,  2,  3,  4,  5,  1,  8, 14],
       [ 1,  5,  5,  9,  8,  2, 28,  0],
       [10,  9,  5,  7,  3,  2,  1,  9]])

7. Obtener el estimador de la varianza del termino de perturbación

In [55]:
import random 

random.seed(175)

x1 = np.random.rand(500) # uniform distribution  [0,1]
x2 = np.random.rand(500) # uniform distribution [0,1]
x3 = np.random.rand(500) # uniform distribution [0,1]
x4 = np.random.rand(500) # uniform distribution [0,1]
e = np.random.normal(0,1,500) # normal distribution mean = 0 and sd = 1

# Poblacional regression (Data Generating Process GDP)


Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

In [56]:
X = np.column_stack((np.ones(500),x1,x2,x3,x4))
X

array([[1.        , 0.37424465, 0.57037655, 0.14784565, 0.47683744],
       [1.        , 0.93054897, 0.87738409, 0.03275924, 0.00993955],
       [1.        , 0.42867408, 0.10438909, 0.00255332, 0.86292846],
       ...,
       [1.        , 0.74025965, 0.87772172, 0.7077111 , 0.31073278],
       [1.        , 0.27214903, 0.33379879, 0.05516717, 0.32951191],
       [1.        , 0.70702794, 0.26706477, 0.56886125, 0.1280158 ]])

In [57]:
beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
beta

array([1.23128395, 0.6800836 , 0.69043495, 0.64550257, 1.43834363])

In [59]:
Y_hat = X@beta
Y_hat


array([2.66090034, 2.50535435, 2.83772786, 2.30021509, 3.61321014,
       3.24225655, 3.35748183, 3.45580258, 2.07523316, 2.97779078,
       3.15405194, 3.29916949, 2.97011106, 3.64734305, 3.10942661,
       3.73446711, 3.12475125, 2.61221407, 2.99086271, 2.65685285,
       3.31060973, 3.32012963, 2.85448793, 2.63689241, 4.06333847,
       2.15298135, 3.40756425, 2.92126176, 3.29815435, 2.35947647,
       3.56424077, 1.76170228, 2.90029625, 2.86402317, 3.17272202,
       3.72454326, 3.1411878 , 3.28352176, 2.88435152, 2.65609984,
       3.4163954 , 2.12829728, 2.32076242, 3.14151798, 2.31536517,
       3.37131757, 2.27687613, 3.59233155, 2.81835438, 2.30661279,
       2.84445716, 1.98827988, 3.02834999, 2.73764619, 2.01674923,
       3.24124099, 2.55750508, 2.64561403, 3.13361503, 2.76698779,
       2.54908219, 2.10179346, 3.12142839, 3.45515746, 2.93529615,
       3.65048135, 3.13290167, 3.31538118, 2.70836922, 2.74606277,
       3.5873466 , 2.86355643, 2.93241185, 3.82922097, 3.69129

In [63]:
U_hat = Y - Y_hat
U_hat


array([ 5.51264503e-01,  8.66938364e-01, -1.31017925e+00,  5.90329222e-01,
       -1.25521722e+00, -1.51644857e+00,  9.44104231e-01, -1.93817348e-01,
       -2.01786169e+00, -2.53734886e+00,  1.58187310e-01, -1.04663915e+00,
        1.71968484e+00, -1.18871680e+00,  2.11274175e-02, -2.05284942e-01,
       -6.06438393e-01, -8.12099406e-01,  3.68577558e-01, -1.38794731e+00,
       -3.56918679e-01, -9.43153661e-01, -9.92109471e-01, -3.19025853e-01,
        7.75362372e-01, -2.06669738e-01, -3.71020773e-01,  1.59538628e-01,
        4.08822344e-01, -1.61211142e+00, -1.17675200e+00, -1.30035984e+00,
       -1.45768123e+00, -2.09869518e-02,  1.27230635e-01,  3.55137342e-01,
        1.10723804e+00, -3.87431584e-01,  1.07147386e+00, -9.64348053e-01,
       -2.35248268e-01, -7.77017183e-01,  2.11842269e+00,  2.08706087e-01,
        1.12264744e-01,  2.58074353e+00,  5.05232042e-01,  4.04533060e-01,
       -6.95634046e-01, -8.51366835e-01,  1.20470251e+00, -9.51700457e-01,
        8.66275878e-01, -

In [64]:
U_hat.T

array([ 5.51264503e-01,  8.66938364e-01, -1.31017925e+00,  5.90329222e-01,
       -1.25521722e+00, -1.51644857e+00,  9.44104231e-01, -1.93817348e-01,
       -2.01786169e+00, -2.53734886e+00,  1.58187310e-01, -1.04663915e+00,
        1.71968484e+00, -1.18871680e+00,  2.11274175e-02, -2.05284942e-01,
       -6.06438393e-01, -8.12099406e-01,  3.68577558e-01, -1.38794731e+00,
       -3.56918679e-01, -9.43153661e-01, -9.92109471e-01, -3.19025853e-01,
        7.75362372e-01, -2.06669738e-01, -3.71020773e-01,  1.59538628e-01,
        4.08822344e-01, -1.61211142e+00, -1.17675200e+00, -1.30035984e+00,
       -1.45768123e+00, -2.09869518e-02,  1.27230635e-01,  3.55137342e-01,
        1.10723804e+00, -3.87431584e-01,  1.07147386e+00, -9.64348053e-01,
       -2.35248268e-01, -7.77017183e-01,  2.11842269e+00,  2.08706087e-01,
        1.12264744e-01,  2.58074353e+00,  5.05232042e-01,  4.04533060e-01,
       -6.95634046e-01, -8.51366835e-01,  1.20470251e+00, -9.51700457e-01,
        8.66275878e-01, -

In [65]:
U_hat.T@U_hat

474.91396516364387

In [68]:
SCR = U_hat.T@U_hat
SCR

474.91396516364387

In [70]:
Estimador_de_la_varianza_del_termino_de_pertubacion = SCR/(500-5)
Estimador_de_la_varianza_del_termino_de_pertubacion

0.9594221518457452

8. Matriz de varianza y covarianza de los coeficientes

In [75]:
Estimador_de_la_varianza_del_termino_de_pertubacion*np.linalg.inv(X.T @ X)

array([[ 2.50741761e-02, -1.08046818e-02, -1.27547099e-02,
        -1.05369151e-02, -1.18018969e-02],
       [-1.08046818e-02,  2.31386722e-02,  2.02427313e-04,
        -9.46009485e-04, -9.01658664e-04],
       [-1.27547099e-02,  2.02427313e-04,  2.49619724e-02,
        -6.56820448e-04,  8.08604309e-04],
       [-1.05369151e-02, -9.46009485e-04, -6.56820448e-04,
         2.30652715e-02,  7.22636139e-05],
       [-1.18018969e-02, -9.01658664e-04,  8.08604309e-04,
         7.22636139e-05,  2.26968370e-02]])

9. Matriz generador de residuos

In [90]:
I = np.eye(500)
I

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [94]:
M = I-X@np.linalg.inv(X.T@X)@X.T
M

array([[ 9.94692817e-01, -5.74025900e-03, -5.10696861e-03, ...,
        -4.89566417e-04, -6.01352175e-03, -6.96624911e-04],
       [-5.74025900e-03,  9.77933889e-01,  1.17875108e-03, ...,
        -8.33995721e-03, -5.16824792e-03, -5.88584931e-03],
       [-5.10696861e-03,  1.17875108e-03,  9.85777294e-01, ...,
         6.17099610e-03, -7.49458405e-03,  1.55228979e-06],
       ...,
       [-4.89566417e-04, -8.33995721e-03,  6.17099610e-03, ...,
         9.91029217e-01,  2.06586017e-03, -3.22281474e-03],
       [-6.01352175e-03, -5.16824792e-03, -7.49458405e-03, ...,
         2.06586017e-03,  9.90858559e-01, -2.95743118e-03],
       [-6.96624911e-04, -5.88584931e-03,  1.55228979e-06, ...,
        -3.22281474e-03, -2.95743118e-03,  9.91479327e-01]])